name: Deploy FE to s3 bucket
run-name: 'Build and Deploy on ${{ github.ref }} by ${{ github.actor }} - runid : ${{ github.run_id }}'
on: ['workflow_dispatch']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'cloud-resume-challenge'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: NPM build
        run: |
          cd fe
          npm install && npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-southeast-1'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Empty and Upload to S3 bucket
        run: |
          aws s3 rm s3://${{ secrets.S3_FE_BUCKET }} --recursive
          aws s3 cp fe/dist s3://${{ secrets.S3_FE_BUCKET }} --recursive
